Table_1 des génes aprés filtre

In [1]:
import pandas as pd
import glob
import os
from collections import Counter

data = "/home/osidibe/work/fluGenAvi_fugace/analyse_preDESMAN/filters/coverage_by_SAMPLE/out_statbyGENE_5_90_90/stat_beforeFILTER.csv"

my_data = pd.read_csv(data, sep = "\t" , usecols = [0,1], names=["gene_name", "sample_name"], index_col= [0])
list1 = my_data.index.unique()
print(len(list1))
# print(len(set(my_data.index)))

102


Table_2 des génes aprés filtre

In [ ]:
import pandas as pd
import glob
import os
from collections import Counter

data = "/home/osidibe/work/fluGenAvi_fugace/analyse_preDESMAN/filters/coverage_by_SAMPLE/out_statbyGENE_5_90_90/stat_afterFILTER.csv"

my_data = pd.read_csv(data, sep = "\t" , usecols = [0,1], names=["gene_name", "sample_name"], index_col= [0])

list2 = my_data.index.unique()
print(len(list2))
# print(len(set(my_data.index)))


Comparaison des deux tables pour ressortir les génes différents

In [3]:
set_difference = set(list1).symmetric_difference(set(list2))
list_difference = list(set_difference)

print(list_difference)

['ant_6__Ia_5_AB247327', 'mph_B__1_D85892', 'erm_36__1_AF462611', 'lnu_B__1_AJ238249', 'lsa_E__1_JX560992', 'mef_B__1_FJ196385', 'tet_M__1_X92947', 'OqxA_1_EU370913', 'msr_A__1_X52085', 'cat_2_M35190', 'cmlA1_1_M64556', 'tet_M__10_EU182585', 'cmr_1_U43535', 'blaCARB_1_1_AF313471', 'fosD_1_KC989517', 'ant_6__Ia_2_KF421157', 'tet_Z__1_AF121000', 'ant_3____Ia_1_X02340', 'mef_A__3_AF227520', 'dfrA14_5_DQ388123', 'aac_6___Ii_1_L12710', 'erm_Q__1_L22689', 'tet_W__2_AY049983', 'mph_C__1_AB013298', 'lnu_G__1_KX470419', 'cmx_1_U85507', 'fosA7_1_LAPJ01000014', 'blaSHV_100_1_AM941846', 'lnu_A__1_M14039', 'tetA_P__1_AB054980', 'tet_J__1_ACLE01000065', 'tet_D__1_AF467077', 'aac_6___Iid_1_AJ584700', 'fosA6_1_KU254579', 'aadA9_1_AJ420072', 'tet_K__1_U38656', 'aph_3___Ia_2_EU287476', 'dfrA16_1_AF077008', 'Cfr_E__1_NG_070225', 'dfrA15_4_AJ867237', 'catS_1_X74948', 'catA1_1_V00622', 'dfrG_1_AB205645', 'OqxB_1_EU370913', 'tet_33__1_AY255627', 'mef_A__2_U83667', 'str_1_X92946', 'aadA2_1_NC_010870', 'tet_4

Création de table de comptage à partir de fichier fasta : e.g : vat_E_ref

In [193]:
import pandas as pd
import numpy as np
from Bio.SeqIO.FastaIO import SimpleFastaParser 

outputfile = "/home/osidibe/work/fasta to freq"
fasta_path = "/home/osidibe/work/fasta to freq/vat_E__3_AF153312.fasta" 


table = pd.DataFrame(columns=["coordinate"], data = range(1,length_seq+1,1), index=None)

df = pd.DataFrame(columns = ["A", "C", "G","T"])


table = pd.concat([table,df])
table["coordinate"] = table["coordinate"].astype(np.int64)
table = table.set_index("coordinate")
table =table.fillna(0)




with open(fasta_path) as handle :
    for sequence in SimpleFastaParser(handle):
        seq = sequence[1]
        # print(seq)
        length_seq = len(seq)

    for index in range (1, length_seq+1):
        if seq[index-1] == "A":
            table.loc[index,"A"] =50
        elif seq[index-1] == "C":
            table.loc[index,"C"] =50
        elif seq[index-1] == "G":
            table.loc[index,"G"] =50
        elif seq[index-1] == "T":
            table.loc[index,"T"] =50
            
    table.to_csv(f"{outputfile}/fre_allelic_vat_E.freq", sep = "\t")
        

ATGACTATACCTGACGCAAATGCAATCTATCATAACTCAGCCATCAAAGAGGTTGTCTTTATCAAGAACGTGATCAAAAGTCCCAATATTGAAATTGGGGACTACACCTATTATGATGACCCAGTAAATCCCACCGATTTTGAGAAACACGTTACCCATCACTATGAATTTCTAGGCGACAAATTAATCATCGGTAAATTTTGTTCTCTCGCCAGTGGCATTGAATTTATCATGAACGGTGCCAACCACGTAATGAAAGGTATTTCGACTTATCCATTTAATATATTAGGTGGCGATTGGCAACAATACACTCCTGAACTGACTGATTTGCCGTTGAAAGGTGATACTGTAGTCGGAAATGACGTGTGGTTTGGGCAAAATGTGACCGTCCTACCAGGCGTAAAAATAGGTGACGGTGCCATTATCGGAGCAAATAGTGTTGTAACAAAAGACGTCGCTCCATATACAATTGTCGGTGGCAATCCAATTCAACTCATCGGACCAAGATTTGAACCGGAAGTTATTCAAGCATTAGAAAATCTGGCATGGTGGAATAAAGATATTGAATGGATAACTGCTAATGTTCCTAAACTAATGCAAACAACACCCACACTTGAATTGATAAACAGTTTAATGGAAAAATAA


Filtre des genes présents dans moins de 2 échantillons

In [ ]:
import pandas as pd


data = "/home/osidibe/work/fluGenAvi_fugace/analyse_preDESMAN/filters/coverage_by_SAMPLE/out_statbyGENE_5_90_90/stat_afterFILTER.csv"
outputdirectory = "/home/osidibe/work/fluGenAvi_fugace/analyse_preDESMAN/filters/coverage_by_SAMPLE/out_statbyGENE_5_90_90"


my_data = pd.read_csv(data, sep = "\t" , usecols = [0,1], names=["gene_name", "sample_name"])

gene_decompte = my_data.gene_name.value_counts()
# print(gene_decompte)
gene_decompte.to_csv(f"{outputdirectory}/Prevalence.csv", sep ='\t')
# print(len(gene_decompte))
gene_decompte = gene_decompte[gene_decompte < 2]
genes_list = gene_decompte.index


my_data_series = pd.read_csv(data, sep = "\t" , usecols = [0,1], names=["gene_name", "sample_name"], index_col= [0])

for gene in genes_list:
    my_data_series.drop(labels =gene, inplace =True)


my_data_series.to_csv(f"{outputdirectory}/stat_afterFilter_final.csv", sep='\t')



In [ ]:
import pandas as pd

data = "/home/osidibe/work/fluGenAvi_fugace/analyse_preDESMAN/filters/coverage_by_SAMPLE/out_statbyGENE_5_90_90/stat_afterFilter_final.csv"
genes = pd.read_csv(data)


In [17]:
import pandas

file = open("/home/osidibe/work/fluGenAvi_fugace/snakemake/genes_list_test.txt", "r")

genes_list = file.read().split(",")
genes_list

["['aph_2____Ib_2_AF207840'",
 "'aph_6__Id_1_M28829'",
 "'aph_3___IIIa_1_AF330699']"]

In [26]:
import pandas as pd

outputfile = "/home/osidibe/work/fluGenAvi_fugace/snakemake/genes_list.txt"
data = "/home/osidibe/work/fluGenAvi_fugace/analyse_preDESMAN/filters/coverage_by_SAMPLE/out_statbyGENE_5_90_90/stat_afterFilter_final.csv"
file = open(outputfile, "w")

genes = pd.read_csv(data, sep = "\t")
genes_list = genes.gene_name.unique()

for gene in genes_list:
    file.write(f"{gene}")

print(genes_list)
print(len(genes_list))




['aph_2____Ib_2_AF207840' 'aph_6__Id_1_M28829' 'aph_3___IIIa_1_AF330699'
 'ant_6__Ia_3_KF864551' 'ant_6__Ib_1_FN594949' 'aph_2____Id_1_AF016483'
 'cepA_1_L13472' 'blaTEM_1A_1_HM749966' 'erm_B__18_X66468'
 'erm_F__3_M17808' 'erm_G__1_M15332' 'erm_X__1_M36726' 'lnu_C__1_AY928180'
 'msr_D__2_AF274302' 'vat_E__3_AF153312' 'cat_3_S48276'
 'tet_32__1_EU722333' 'tet_44__1_NZ_ABDU01000081' 'tet_40__1_FJ158002'
 'tet_A__6_AF534183' 'tet_B__1_AP000342' 'tet_O__1_M18896'
 'tet_L__2_M29725' 'tet_Q__3_U73497' 'tet_X__1_GU014535'
 'tet_W__1_DQ060146' 'dfrA1_7_AJ400733' 'dfrD_1_Z50141']
28


In [11]:
import pandas as pd

#oucrir le fichier all.fit
inputfile = "/home/osidibe/save/fuGace_project/Test_DESMAN/DESMAN_preFilter/DESMAN_erm_B__18_X66468/all_fit.txt"
optimal_variant = 5

fichier_fit = pd.read_csv(inputfile, names = ["H", "G", "G2", "LP", "Dev"] )
fichier_fit



fichier_fit_opt = fichier_fit[fichier_fit.G == 5]
fichier_fit_opt

H  G  G2           LP          Dev
25  Fit  5   5 -1774.352740  4944.251535
26  Fit  5   5 -1778.721161  4947.820663
27  Fit  5   5 -1786.642684  4944.686947
28  Fit  5   5 -1681.136233  5052.254257
29  Fit  5   5 -1775.729639  4960.884067

In [56]:
import pandas as pd 
import os
import glob
import fnmatch

directoryectory = "/home/osidibe/work/fluGenAvi_fugace/snakemake/snk_DESMAN_G2"
pattern_DESfile = "desman*"


gene_name_directory = glob.glob(f"{directoryectory}/*")

for gene in gene_name_directory:
    genes_rep = os.path.basename(gene)
    with open (f"{directoryectory}/{genes_rep}/allfit_bis.txt", "w") as bis_allfit:
        for DEsfile in os.listdirectory(gene):
            if fnmatch.fnmatch(DEsfile, pattern_DESfile):
                fit_directory = os.path.join(f"{directoryectory}/{genes_rep}/{DEsfile}/fit.txt")           
                with open (fit_directory, "r") as fitfile:
                    bis_allfit.write(fitfile.read())
                    
            

read_fit = pd.read_csv(f"{gene_name}/allfit_bis.txt")
print(read_fit)            
sort_fit = read_fit.sort_values(by=read_fit.columns[1]).reset_index(drop=True)      
print(sort_fit)  
sort_fit.to_csv(f"{gene_name}/allfit_bis.txt", index=False)

        
        



In [17]:
import pandas as pd 
import os
import glob
import fnmatch

fit_file = "/home/osidibe/work/fluGenAvi_fugace/snakemake/snk_DESMAN/DESMAN_blaTEM_1A_1_HM749966"

read_ff = pd.read_csv(f"{fit_file}/all_fit.txt", header=None)
sort_ff = read_ff.sort_values(read_ff.columns[1], ascending=True)
sort_ff.to_csv(f"{fit_file}/fitbis.txt", index=False)

Table du nombre de variant et proportion de bonnes matrices d'erreurs

In [251]:
import pandas as pd
import numpy as np
import glob
import os



inputdirectory="/home/osidibe/work/fluGenAvi_fugace/analyse_postDESMAN/DESMAN"
genes_namesList="/home/osidibe/work/fluGenAvi_fugace/analyse_postDESMAN/genes_list.txt"
genes_namesList



#Ouvrir genes_namesList pour lecture
genes_list = pd.read_table(genes_namesList, header=None, index_col=[0])

table= pd.DataFrame(columns=["gene_name", "Num_PosVariable", "Prop_matriceERRexact"])


#Pour chaque nom de gène ouvrir son répertoire
for gene in genes_list.index:
    list =[]
    df_sel_var = pd.read_csv(f"{inputdirectory}/DESMAN_{gene}/file.outsel_var.csv")
    #Nombre de positions variables du géne
    numb_Pvar = len(df_sel_var)
    
    ##ourvrir chaque sous repertoire du géne
    #Répertoire desman du géne        
    directory_gene = os.path.join(inputdirectory, "DESMAN_" + gene)
    #Nom de fichier de la matrice d'erreur
    matriceERR_file = "Eta_star.csv"
    #Pour chaque sous repertoire
    for desman_file in os.listdirectory(directory_gene):
        #Joindre le fichier desman au chemin du repertoire parent
        path = os.path.join(directory_gene, desman_file)
        #renvoie le chemin que si c'est un repertoire
        if os.path.isdirectory(path) :
            #rajoute le chemin vers le fichier matrice d'erreur
            directory_matriceERR = os.path.join(path, matriceERR_file)
            #print(directory_matriceERR)
            
            ##Ouvrir le fichier pour lecture
            df_matriceERR = pd.read_csv(directory_matriceERR)
            #print(df_matriceERR.shape)
            df = np.genfromtxt(directory_matriceERR , delimiter=",", dtype=float, skip_header=True, usecols=(1,2,3,4))
            #print(df)
            
            if np.array((df[0,0] > 0.9) & (df[1,1] > 0.9) & (df[2,2] > 0.9) & (df[3,3] > 0.9)):
                #print("yes")
                list.append(1)
            else :
                #print("no")
                list.append(0)
                

    Prp_matriceERR = sum(list)/ len(list)
    
    #print(Prp_matriceERR)
    
    #result = pd.DataFrame({"gene_name":gene, "Num_PosVariable":numb_Pvar,"Prop_matriceERRexact":Prp_matriceERR})
    
    result = pd.DataFrame(data=[[gene, numb_Pvar, Prp_matriceERR]], columns=["gene_name","Num_PosVariable", "Prop_matriceERRexact"])
    table = pd.concat([table, result], ignore_index=True)
    
    
table.to_csv(f"{inputdirectory}/Prop_matriceERRexact.csv", index=False)
    
    
#courbe de distribution de la proportion de matrices d'erreurs exactes en fonction du nombre de position variable



    
    

In [169]:
import numpy as np


file = "/home/osidibe/work/fluGenAvi_fugace/analyse_postDESMAN/DESMAN/DESMAN_blaTEM_1A_1_HM749966/desman.3.4/Eta_star.csv"
df = np.genfromtxt(file, delimiter=",", dtype=float, skip_header=True, usecols=(1,2,3,4))
print(df)
list =[]
if np.array((df[0,0] > 0.9) & (df[1,1] > 0.9) & (df[2,2] > 0.9) & (df[3,3] > 0.9)):
    print("yes")
    list.append(1)
else :
    print("no")
    list.append(0)
print(list)

Prp_matriceERR = sum(list)/ len(list)
Prp_matriceERR


[[9.95599666e-01 2.11180472e-09 4.40020174e-03 1.30235028e-07]
 [1.01316924e-20 9.92060171e-01 1.46695963e-13 7.93982857e-03]
 [1.59766854e-04 3.98504870e-14 9.99840233e-01 1.14161681e-25]
 [1.27073740e-17 1.46130483e-04 2.01902764e-20 9.99853870e-01]]
yes
[1]


1.0

Analse comparative des sorties desman.py & desman.py+AddPositions

In [176]:
import pandas as pd

file_1 ="/home/osidibe/work/fluGenAvi_fugace/Analyse_postDESMAN_addPos/DESMAN/DESMAN_iter_erm_B__18_X66468/desman.2.1/Filtered_Tau_star_haplotypes"
file_2 ="/home/osidibe/work/fluGenAvi_fugace/Analyse_postDESMAN_addPos/DESMAN/DESMAN_iter_erm_B__18_X66468/desman.2.2/Filtered_Tau_star_haplotypes"

#creer un df avec pour index les positions variables 
colonnes_exclus = [0,1]
name =["Variab_Pos"]
df = pd.read_csv(file_1, header=None, sep="\t")
len(df.columns)

# df1 = [pd.read_csv(file) for file in files ]
# df1 = df1.iloc[:,2:]
# df1

# df=df.iloc[:,]
# df1 = pd.read_csv(file1) usecols= lambda col: col not in colonnes_exclus)



4

In [25]:
import pandas as pd
import os
import fnmatch

#ouvrir repertoire parent e
directory = "/home/osidibe/work/fluGenAvi_fugace/Analyse_postDESMAN_addPos/DESMAN/DESMAN_iter_erm_B__18_X66468"

    #Ouvrir les sous-repertoires desman
for desman_file in os.listdirectory(directory):

#extraire les positions variables
    Pos_var = pd.read_csv(f"{directory}/file.outsel_var.csv", usecols=[1])

    if fnmatch.fnmatch(desman_file, "desman.*"):
        
        #Pour chaque repertoire, ouvrir le fichier filtered tau haplotypes
        haplo_file = pd.read_csv(f"{directory}/{desman_file}/Filtered_Tau_star_haplotypes", sep ="\t", header=None)
        haplo_file = haplo_file.iloc[:,2:]

        #Pour au moins 2 variants par fichier créer des soucolonnes
        # colnames_doublons = haplo_file.columns.duplicated()

        list_var = [i for i in range(1, len(haplo_file.columns)+1)]
        # print(list_var)
        if len(haplo_file.columns)> 1:
            haplo_file.columns = pd.MultiIndex.from_product([[desman_file], list_var])
        else:
            haplo_file.columns = [desman_file]
            # print(haplo_file)

        result = pd.concat([Pos_var,haplo_file], axis=1) 
        result.to_csv(f"{directory}/{desman_file}/haplo.csv")




    Unnamed: 0  Position desman.1.1
0            0        18          A
1            1       123          T
2            2       246          T
3            3       248          C
4            4       323          A
5            5       334          C
6            6       346          C
7            7       377          G
8            8       397          A
9            9       404          A
10          10       421          C
11          11       596          C
12          12       643          A
13          13       700          A
    Unnamed: 0  Position desman.1.2
0            0        18          A
1            1       123          T
2            2       246          T
3            3       248          C
4            4       323          A
5            5       334          C
6            6       346          C
7            7       377          G
8            8       397          A
9            9       404          A
10          10       421          C
11          11       596    

In [89]:
import pandas as pd
import os, sys
import fnmatch
import glob

#ouvrir repertoire parent e
directory = "/home/osidibe/work/fluGenAvi_fugace/Analyse_postDESMAN_P2/DESMAN_iterAddPost/DESMAN_erm_B__18_X66468"

#extraire les positions variables
Pos_var = pd.read_csv(f"{directory}/file.outsel_var.csv", usecols=[1])
# stocker les positions variables dans une liste
list_PosVar = [x for x in Pos_var.values]
# print(list_PosVar)

nb_var = 5
for i in range(1, nb_var+1):
    # print(i)
    result = pd.DataFrame(Pos_var)
    # print(result)
    ##Ouvrir les sous-repertoires desman
    for desman_file in os.listdir(directory):

        if fnmatch.fnmatch(desman_file, f"desman.{i}.*"):
            # print(desman_file)
            
            #Pour chaque repertoire, ouvrir le fichier filtered tau haplotypes
            
            haplo_file = pd.DataFrame()
            for x in list_PosVar:
                try:
                    file = pd.read_csv(f"{directory}/{desman_file}/Filtered_Tau_star_haplotypes", sep ="\t", header=None)
                    
                except FileNotFoundError :
                    print(f"{desman_file}/Filtered_Tau_star_haplotypes not found")
                    sys.exit()

            
                file = file[file.iloc[:,1].isin(x)]
                # print(file)
                
                haplo_file = pd.concat([haplo_file, file], ignore_index=True)
                
                # print(haplo_file)
                newfile = haplo_file.iloc[:,2:]
                # print(newfile)
            #Pour au moins 2 variants par fichier créer des soucolonnes
            list_var = [i for i in range(1, len(newfile.columns)+1)]
            # print(list_var)
            if len(newfile.columns)> 1:
                newfile.columns = pd.MultiIndex.from_product([[desman_file], list_var])
            else:
                newfile.columns = [desman_file]
                # print(haplo_file)

            result = pd.concat([result,newfile], axis=1)
            print(result) 
    
            result.to_csv(f"{directory}/haplo_{i}Var.csv")
    print("okkkk")
        
###Concatener en ligne tous les fihier d'un même nombre de variant en un fichier

##Chemin vesr les fichiers haplo
haplo_path = glob.glob(f"{directory}/haplo_*")
print(haplo_path)
##Ouvrir un fichier pour écriture
with open(f"{directory}/all_haplo.csv", "w") as outputfile:
    outputfile.write(f"Gene : erm_B" + "\n")
    for file in haplo_path:
        with open (file, "r") as haplo_file:
            outputfile.write(haplo_file.read() + "\n")





    Position desman.1.1
0         18          A
1        123          T
2        246          T
3        248          C
4        323          A
5        334          C
6        346          C
7        377          G
8        397          A
9        404          A
10       421          C
11       596          C
12       643          A
13       700          A
    Position desman.1.1 desman.1.2
0         18          A          A
1        123          T          T
2        246          T          T
3        248          C          C
4        323          A          A
5        334          C          C
6        346          C          C
7        377          G          G
8        397          A          A
9        404          A          A
10       421          C          C
11       596          C          C
12       643          A          A
13       700          A          A
    Position desman.1.1 desman.1.2 desman.1.3
0         18          A          A          A
1        123          T

In [64]:
import pandas as pd
import os
import fnmatch
import glob

#ouvrir repertoire parent e
directory = "/home/osidibe/work/fluGenAvi_fugace/Analyse_postDESMAN_P2/DESMAN_iterAddPost/DESMAN_ant_6__Ib_1_FN594949"

#extraire les positions variables
Pos_var = pd.read_csv(f"{directory}/file.outsel_var.csv", usecols=[1])

list_PosVar = [x for x in Pos_var.values]
print(list_PosVar)
file = pd.read_csv("/home/osidibe/work/fluGenAvi_fugace/Analyse_postDESMAN_P2/DESMAN_iterAddPost/DESMAN_ant_6__Ib_1_FN594949/desman.1.1/Filtered_Tau_star_haplotypes", sep ="\t", header=None)
    

haplo_file = pd.DataFrame()
for i in list_PosVar:
    file = file[file.iloc[:,1].isin(i)]
    
    haplo_file = pd.concat([haplo_file, file], ignore_index=True)
    
print(haplo_file)
newfile = haplo_file.iloc[:,2:]
print(newfile)

   


[array([49]), array([460]), array([650])]
                      0   1  2
0  ant_6__Ib_1_FN594949  49  G
   2
0  G
